import secrets
from datetime import datetime

import structlog

logger = structlog.get_logger()


def generate_share_token() -> str:
    """Generate a secure share token for proposal links."""
    return secrets.token_urlsafe(32)


def format_proposal_html(proposal_content: dict) -> str:
    """Format proposal content as HTML for PDF generation."""
    html_parts = [
        "<html><head><style>",
        "body { font-family: Arial, sans-serif; margin: 40px; color: #1f2937; }",
        "h1 { color: #1e40af; } h2 { color: #374151; border-bottom: 1px solid #e5e7eb; }",
        "table { border-collapse: collapse; width: 100%; margin: 16px 0; }",
        "th, td { border: 1px solid #d1d5db; padding: 8px 12px; text-align: left; }",
        "th { background: #f3f4f6; } .badge { padding: 2px 8px; border-radius: 4px; font-size: 12px; }",
        "</style></head><body>",
        "<h1>STravel — Trip Proposal</h1>",
    ]

    # Itinerary
    itinerary = proposal_content.get("itinerary", "")
    if itinerary:
        html_parts.append("<h2>Itinerary</h2>")
        html_parts.append(f"<pre>{itinerary}</pre>")

    # Accommodation tables
    tables = proposal_content.get("accommodation_tables", [])
    for table in tables:
        dest = table.get("destination", "")
        html_parts.append(f"<h2>Accommodation — {dest}</h2>")
        html_parts.append("<table><tr><th>Hotel</th><th>Price/Night</th><th>Rating</th><th>Why</th></tr>")
        for opt in table.get("options", []):
            html_parts.append(
                f"<tr><td>{opt.get('name', '')}</td><td>${opt.get('price_per_night', 0)}</td>"
                f"<td>{opt.get('rating', '-')}</td><td>{opt.get('why_it_fits', '')}</td></tr>"
            )
        html_parts.append("</table>")

    # Budget breakdown
    breakdowns = proposal_content.get("budget_breakdown", [])
    if breakdowns:
        html_parts.append("<h2>Budget Breakdown</h2>")
        html_parts.append("<table><tr><th>Category</th><th>Allocated</th></tr>")
        for bd in breakdowns:
            html_parts.append(f"<tr><td>{bd.get('category', '')}</td><td>${bd.get('allocated', 0):.2f}</td></tr>")
        html_parts.append("</table>")

    # Booking actions
    actions = proposal_content.get("booking_actions", [])
    if actions:
        html_parts.append("<h2>Booking Actions</h2>")
        html_parts.append("<ol>")
        for action in sorted(actions, key=lambda a: a.get("priority", 99)):
            html_parts.append(f"<li><strong>{action.get('item', '')}</strong> — {action.get('reason', '')}</li>")
        html_parts.append("</ol>")

    html_parts.append(f"<p><small>Generated by STravel on {datetime.utcnow().strftime('%Y-%m-%d')}</small></p>")
    html_parts.append("</body></html>")

    return "\n".join(html_parts)


def generate_pdf_bytes(html_content: str) -> bytes:
    """Generate PDF from HTML content. Uses WeasyPrint if available, falls back to HTML bytes."""
    try:
        from weasyprint import HTML

        pdf = HTML(string=html_content).write_pdf()
        logger.info("export.pdf_generated", size_bytes=len(pdf))
        return pdf
    except ImportError:
        logger.warning("export.weasyprint_not_installed", fallback="html_bytes")
        return html_content.encode("utf-8")
