from typing import AsyncIterator, Protocol


class LLMServiceProtocol(Protocol):
    async def generate(self, prompt: str, **kwargs) -> str: ...
    async def stream(self, prompt: str, **kwargs) -> AsyncIterator[str]: ...


class VectorStoreProtocol(Protocol):
    async def search(self, query: str, filters: dict, limit: int = 10) -> list[dict]: ...
    async def get_by_id(self, entity_id: str) -> dict | None: ...


class CacheProtocol(Protocol):
    async def get(self, key: str) -> str | None: ...
    async def set(self, key: str, value: str, ttl: int = 3600) -> None: ...
