apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stravel-ingress
  namespace: stravel
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - stravel.example.com
      secretName: stravel-tls
  rules:
    - host: stravel.example.com
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: stravel-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stravel-frontend
                port:
                  number: 3000
