"""create initial tables

Revision ID: 90e256b6caf0
Revises: 
Create Date: 2026-05-24 23:33:49.828018

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '90e256b6caf0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisory_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ARCHIVED', name='sessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisory_sessions_tenant_id'), 'advisory_sessions', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_users_email'), 'tenant_users', ['email'], unique=True)
    op.create_index(op.f('ix_tenant_users_tenant_id'), 'tenant_users', ['tenant_id'], unique=False)
    op.create_table('traveler_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('advisory_session_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('traveler_count', sa.Integer(), nullable=True),
    sa.Column('traveler_ages', sa.JSON(), nullable=True),
    sa.Column('nationalities', sa.JSON(), nullable=True),
    sa.Column('travel_start_date', sa.Date(), nullable=True),
    sa.Column('travel_end_date', sa.Date(), nullable=True),
    sa.Column('date_flexibility', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('budget_total', sa.Float(), nullable=True),
    sa.Column('budget_currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('destination_preferences', sa.JSON(), nullable=True),
    sa.Column('accommodation_style', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dietary_requirements', sa.JSON(), nullable=True),
    sa.Column('accessibility_needs', sa.JSON(), nullable=True),
    sa.Column('activity_preferences', sa.JSON(), nullable=True),
    sa.Column('special_interests', sa.JSON(), nullable=True),
    sa.Column('passport_expiry_date', sa.Date(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['advisory_session_id'], ['advisory_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traveler_profiles_advisory_session_id'), 'traveler_profiles', ['advisory_session_id'], unique=True)
    op.create_index(op.f('ix_traveler_profiles_tenant_id'), 'traveler_profiles', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traveler_profiles_tenant_id'), table_name='traveler_profiles')
    op.drop_index(op.f('ix_traveler_profiles_advisory_session_id'), table_name='traveler_profiles')
    op.drop_table('traveler_profiles')
    op.drop_index(op.f('ix_tenant_users_tenant_id'), table_name='tenant_users')
    op.drop_index(op.f('ix_tenant_users_email'), table_name='tenant_users')
    op.drop_table('tenant_users')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_advisory_sessions_tenant_id'), table_name='advisory_sessions')
    op.drop_table('advisory_sessions')
    # ### end Alembic commands ###
